### ISSUE TITLE
Change license to GPL

### ISSUE THREAD

**Issue by johnhooks** [wp-blocks/create-pkg-cli#2]
I would be good with changing the license to GPL.

**Comment by erikyo** [comment]
GPL has the difference that if someone uses, modifies and distribute this package, it must be GPL compliant, so I ~~can't~~ can say that it's OK with me!

**Comment by johnhooks** [comment]
Do you think all of these should be MIT, that's what I've typically use, but it seemed like the WP ecosystem uses GPL

**Comment by erikyo** [comment]
Generally for node / npm stuff I use MIT (or ISC) and for WP I use GPL... this one is in the middle so I don't know 😅

Do you think it might limit the use of the module in some way?

**Comment by johnhooks** [comment]
@erikyo after reading that again, was the _can't_ a typo?

**Comment by johnhooks** [comment]
No, I don't. I was just thinking to keep it consistent. But I'm down to keep it as is.

**Comment by erikyo** [comment]
yes excuse me, I meant to say that it can only be good for me! pardon! And then I had also changed it to GPL! But, if it's better for you the MIT one, i'll put it back as it was!

**Comment by johnhooks** [comment]
No no, let's leave it GLP. I'm good with the conditions of that puts on the users of the package.
